### PR TITLE
CI: Add Travis CI that ensures that we can build

### LINKED ISSUE #20: Set up CI for this template
CI should

* run the local version of the template (not 100% sure how to do this with `npm init` and local packages)
* verify that it builds afterwards (`npm run build`)

am I missing anything else it should do?

### PR DESCRIPTION
**Pull request by fitzgen**
Fix #20

### CODE REVIEW

**Comment by xtuc** [comment]
Have you seen https://github.com/rustwasm/rust-webpack-template/pull/31?

**Comment by fitzgen** [comment]
> Have you seen #31?

yes, but it wasn't actually passing CI yet, hadn't seen activity for a while, and doesn't use pre-built wasm-pack, so I made this version.

**Comment by fitzgen** [comment]
@xtuc hm I think https://github.com/wasm-tool/wasm-pack-plugin/issues/37 is preventing us from implementing CI since webpack doesn't exit after building, but keeps watching for files. Did you have a plan for fixing that issue already or should I look into it?

**Comment by sendilkumarn** [comment]
@fitzgen It would be better to fix the other PR rather than creating a brand new one. 

I think the build was failing because of `cargo.lock` initially. Now it is the time out, same as here. I would prefer to close this and work on #31

**Comment by fitzgen** [comment]
@xtuc fix for the file watching over at https://github.com/wasm-tool/wasm-pack-plugin/pull/38

@sendilkumarn that PR was inactive, it was easier to create a new one. It still doesn't install wasm-pack pre-built binaries, but this PR does. Therefore, it makes more sense to continue with this PR.

**Comment by sendilkumarn** [comment]
> It still doesn't install wasm-pack pre-built binaries, but this PR does
@fitzgen it does install `wasm-pack`.

**Comment by fitzgen** [comment]
Woo, green! Merging now so that we can start relying on this stuff for dependabot.

**Comment by xtuc** [comment]
Thanks

**Pull request merged**
